name: Build

on:
  push:
    paths:
      - '**.java'
      - '**.gradle'
      - '**.xml'
  workflow_dispatch:

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip build]')"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '21'
    - name: Gradle Build
      run: bash ./gradlew build
    - name: Archive Lint Report
      uses: actions/upload-artifact@v4
      with:
        name: lint-report
        path: /home/runner/work/BatteryTile/BatteryTile/app/build/reports/lint-results-debug.html
